language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - nightly

matrix:
  allow_failures:
    - python: nightly

install:
  - sudo apt-get install pandoc
  - python -m pip install -r requirements.txt

before_script:
  - pyformat --in-place pyfancy/pyfancy.py pyfancy/demo.py
  - pyroma .

script:
  - python pyfancy/demo.py
  - python -m pytest
